---
title: "visualizer"
author: "Wufang Hong"
date: "4/29/2024"
output: pdf_document
---

# Dataloader

```{r}
EPB_Power_path = './Data/EPB/EPB_Power_summary.csv'
EPB_FDR_path = './Data/EPB/EPB_FDR_summary.csv'
Welch_Data_path = './Data/Welch Property Simulation Data/Welch Fails/Welch_Fails.csv'
Pooled_t_test_Data_path = './Data/Pooled_t_test.csv'
```

```{r}
EPB_Power_Data = read.csv(EPB_Power_path)
EPB_FDR_Data = read.csv(EPB_FDR_path)
Welch_Data = read.csv(Welch_Data_path)
Pooled_t_test_Data = read.csv(Pooled_t_test_Data_path)
```

```{r}
Power_1D_NPMLE = EPB_Power_Data[,c(1,2,5)]
Power_2D_NPMLE = EPB_Power_Data[, c(1,2,6)]
Power_Welch = Welch_Data[, c(2,3,4)]
Power_Pooled_t = Pooled_t_test_Data[, c(2,3,4)]
```

```{r}
FDR_1D_NPMLE = EPB_FDR_Data[,c(1,2,5)]
FDR_2D_NPMLE = EPB_FDR_Data[, c(1,2,6)]
FDR_Welch = Welch_Data[, c(2,3,5)]
FDR_Pooled_t = Pooled_t_test_Data[, c(2,3,5)]
```

```{r}
Full_FDR_Data = data.frame('n1' = FDR_Welch$n1, 'n2' = FDR_Welch$n2, 'Welch' = FDR_Welch$fdr, 'Pooled_t' = FDR_Pooled_t$fdr, '1D_NPMLE' = rep(0, length(FDR_Welch$n1)), '2D_NPMLE' = rep(0, length(FDR_Welch$n1)))

Full_Power_Data = data.frame('n1' = Power_Welch$n1, 'n2' = Power_Welch$n2, 'Welch' = Power_Welch$power, 'Pooled_t' = Power_Pooled_t$power, '1D_NPMLE' = rep(0, length(Power_Welch$n1)), '2D_NPMLE' = rep(0, length(Power_Welch$n1)))
```

```{r}
for (i in c(1:nrow(Full_FDR_Data))) {
  n1 = Full_FDR_Data[i, 1]
  n2 = Full_FDR_Data[i, 2]
  for (j in c(1:nrow(EPB_FDR_Data))) {
    n1_EPB = EPB_FDR_Data[j, 1]
    n2_EPB = EPB_FDR_Data[j, 2]
    if (n1 == n1_EPB & n2 == n2_EPB) {
      Full_FDR_Data[i, 5] = EPB_FDR_Data[j, 5]
      Full_FDR_Data[i, 6] = EPB_FDR_Data[j, 6]
    }
  }
}

for (i in c(1:nrow(Full_Power_Data))) {
  n1 = Full_Power_Data[i, 1]
  n2 = Full_Power_Data[i, 2]
  for (j in c(1:nrow(EPB_Power_Data))) {
    n1_EPB = EPB_Power_Data[j, 1]
    n2_EPB = EPB_Power_Data[j, 2]
    if (n1 == n1_EPB & n2 == n2_EPB) {
      Full_Power_Data[i, 5] = EPB_Power_Data[j, 5]
      Full_Power_Data[i, 6] = EPB_Power_Data[j, 6]
    }
  }
}
```

# Define Plotter

```{r}
Plotter = function(n1, length_n2, Full_FDR_Data, Full_Power_Data) {
  n2_range = c(n1: (n1 + length_n2 - 1))
  FDR_n1 = Full_FDR_Data[Full_FDR_Data$n1 == n1 & (Full_FDR_Data$n2 %in% n2_range), ]
  Power_n1 = Full_Power_Data[Full_Power_Data$n1 == n1 & (Full_Power_Data$n2 %in% n2_range), ]
  
  # FDR with 1D_NPMLE, 2D_NPMLE
  main = substitute(expression(paste('Relation between FDR and ', n[2], ' for 1D_NPMLE and 2D_NPMLE when ', n[1] == N1)), list(N1 = n1))
  plot(FDR_n1$n2, FDR_n1$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = eval(main), cex.main = 0.8, ylim = c(0, 0.2))
  lines(FDR_n1$n2, FDR_n1$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
  abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
  legend('topleft', c('1D_NPMLE', '2D_NPMLE'), col=c('blue', 'black'), lwd=2, lty = 1, cex = 0.7)
  
  # FDR with all algorithms
  main = substitute(expression(paste('Relation between FDR and ', n[2], ' for All Algorithms when ', n[1] == N1)), list(N1 = n1))
  plot(FDR_n1$n2, FDR_n1$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = eval(main), cex.main = 0.8, ylim = c(0, max(FDR_n1[, c(3,4,5,6)])))
  lines(FDR_n1$n2, FDR_n1$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$Pooled_t, type = 'o', pch = 2, col = 'red', lwd = 2)
  abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
  legend('topleft', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'red'), lwd=2, lty = 1, cex = 0.7)
  
  # Power with all algorithms
  main = substitute(expression(paste('Relation between Power and ', n[2], ' for All Algorithms when ', n[1] == N1)), list(N1 = n1))
  plot(Power_n1$n2, Power_n1$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'Power', main = eval(main), cex.main = 0.8, ylim = c(min(Power_n1_3[, c(3,4,5,6)]), max(Power_n1[, c(3,4,5,6)])))
  lines(Power_n1$n2, Power_n1$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
  lines(Power_n1$n2, Power_n1$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
  lines(Power_n1$n2, Power_n1$Pooled_t, type = 'o', pch = 2, col = 'red', lwd = 2)
  legend('bottomright', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'red'), lwd=2, lty = 1, cex = 0.7)
}
```


# n1 = 3

```{r}
n1 = 3
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```
# n1 = 4

```{r}
n1 = 4
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = 5

```{r}
n1 = 5
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = 6

```{r}
n1 = 6
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = 7

```{r}
n1 = 7
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = n2

```{r}
FDR_equ = Full_FDR_Data[Full_FDR_Data$n1 == Full_FDR_Data$n2, ]
main = expression(paste('Relation between FDR and ', n[2], ' for All Algorithms when ', n[1], ' = ', n[2]))
plot(FDR_equ$n2, FDR_equ$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = main, cex.main = 0.8, ylim = c(0, max(FDR_equ[, c(3,4,5,6)])))
lines(FDR_equ$n2, FDR_equ$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
lines(FDR_equ$n2, FDR_equ$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
lines(FDR_equ$n2, FDR_equ$Pooled_t, type = 'o', pch = 2, col = 'red', lwd = 2)
abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
legend('bottomleft', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'red'), lwd=2, lty = 1, cex = 0.7)
```

```{r}
Power_equ = Full_Power_Data[Full_Power_Data$n1 == Full_Power_Data$n2, ]
main = expression(paste('Relation between Power and ', n[2], ' for All Algorithms when ', n[1], ' = ', n[2]))
plot(Power_equ$n2, Power_equ$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'Power', main = main, cex.main = 0.8, ylim = c(0, max(Power_equ[, c(3,4,5,6)])))
lines(Power_equ$n2, Power_equ$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
lines(Power_equ$n2, Power_equ$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
lines(Power_equ$n2, Power_equ$Pooled_t, type = 'o', pch = 2, col = 'red', lwd = 2)
legend('bottomright', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'red'), lwd=2, lty = 1, cex = 0.7)
```


