---
title: "Welch Simulation"
author: "Wufang Hong"
date: "5/13/2024"
output: pdf_document
---

# P value calculation for Welch Approximation

```{r}
Welch_approximation_p = function(n1, n2, Z1, Z2, S1, S2) {
  dfw = (S1/n1 + S2/n2)^2/(1 / (n1-1) * (S1/n1)^2 + 1 / (n2-1) * (S2/n2)^2)
  se2 = S1/n1 + S2/n2
  tw = (Z1 - Z2)/sqrt(se2)
  p = pt(q = abs(tw), df = dfw, lower.tail = FALSE) * 2
  return (p)
}
```

```{r}
P_value_Welch = function (n1, n2, m, Z1_list, Z2_list, S1_list, S2_list) {

  P_value_list_Welch = rep(0, m)
  for (i in 1:m) {
    P_value_list_Welch[i] = Welch_approximation_p(n1 = n1, n2 = n2, Z1 = Z1_list[i], Z2 = Z2_list[i], S1 = S1_list[i], S2 = S2_list[i])
  }
  
  return (P_value_list_Welch)
}
```

# BH, Power, FDR

```{r}
my_BH = function(P, alpha) {
  n = length(P)
  sorted_index = order(P, decreasing = FALSE)
  k_list = which(P[sorted_index][1:n] <= (1:n) * alpha / n)
  if (length(k_list) == 0) {
    return (c())
  }
  else {
    k = max(k_list)
    discovery = sorted_index[1:k]
    return (discovery)
  }
}
```

```{r}
Power = function(discovery, flag_list) {
  dis_count = sum(flag_list)
  true_dis_count = sum(flag_list[discovery])
  power = true_dis_count/dis_count
  return (power)
}
```

```{r}
FDP = function(discovery, flag_list) {
  #null_count = length(flag_list) - sum(flag_list)
  false_null = length(discovery) - sum(flag_list[discovery])
  fdp = false_null/max(length(discovery) ,1)
  return (fdp)
}
```

```{r}
library(matrixsampling)
```

```{r}
ss_generator_F = function(data_generation_parameter) {
  
  n1=data_generation_parameter$n1
  n2=data_generation_parameter$n2
  k=data_generation_parameter$k
  d1=data_generation_parameter$d1
  d2=data_generation_parameter$d2
  m=data_generation_parameter$m
  mu1=data_generation_parameter$mu1
  mu2=data_generation_parameter$mu2
  mean_var2 = data_generation_parameter$mean_var2
  var_var2 = data_generation_parameter$var_var2
  pi0 = data_generation_parameter$pi0
  mu0 = data_generation_parameter$mu0
  
  null_count = as.integer(pi0 * m)
  dis_count = m - null_count
  flag_list = c(rep(0, null_count), rep(1, dis_count)) # 0 for null, 1 for truth
  
  lambda = k * rf(m, d1, d2)
  var2 = abs(rnorm(m, mean_var2, sqrt(var_var2)))
  var1 = lambda * var2
  
  Z1_list = rep(0, m)
  Z2_list = rep(0, m)
  S1_list = rep(0, m)
  S2_list = rep(0, m)

  for (j in 1:m) {
    if (j <= null_count) {
      Z1_list[j] = rnorm(1, mu0, sqrt(var1[j]/n1))
      Z2_list[j] = rnorm(1, mu0, sqrt(var2[j]/n2))
      
      S1_list[j] = var1[j] / (n1-1) * rchisq(1, df = n1-1)
      S2_list[j] = var2[j] / (n2-1) * rchisq(1, df = n2-1)
    }
    else {
      mu1_j = rnorm(1, mean = 0, sd = sqrt(mu1 * var1[j]))
      Z1_list[j] = rnorm(1, mu1_j, sqrt(var1[j]/n1))
      Z2_list[j] = rnorm(1, mu2, sqrt(var2[j]/n2))
      
      S1_list[j] = var1[j] / (n1-1) * rchisq(1, df = n1-1)
      S2_list[j] = var2[j] / (n2-1) * rchisq(1, df = n2-1)
    }
  }
  
  output = list('Z1' = Z1_list, 'S1' = S1_list, 'Z2' = Z2_list, 'S2' = S2_list, 'flag_list' = flag_list)
  
  return (output)
}
```

```{r}
ss_generator_inW = function(data_generation_parameter) {
  
  n1=data_generation_parameter$n1
  n2=data_generation_parameter$n2
  mean_var=data_generation_parameter$mean_var
  v=data_generation_parameter$v
  omega=data_generation_parameter$omega
  mu1=data_generation_parameter$mu1
  mu2=data_generation_parameter$mu2
  pi0 = data_generation_parameter$pi0
  mu0 = data_generation_parameter$mu0
  
  null_count = as.integer(pi0 * m)
  dis_count = m - null_count
  flag_list = c(rep(0, null_count), rep(1, dis_count)) # 0 for null, 1 for truth
  
  sample = rinvwishart(m, v, matrix(c(mean_var, 0.1, 0.1, mean_var),2,2), checkSymmetry = TRUE)
  var2 = sample[2,2,]
  var1 = sample[1,1,]
  
  Z1_list = rep(0, m)
  Z2_list = rep(0, m)
  S1_list = rep(0, m)
  S2_list = rep(0, m)

  for (j in 1:m) {
    if (j <= null_count) {
      Z1_list[j] = rnorm(1, mu0, sqrt(var1[j]/n1))
      Z2_list[j] = rnorm(1, mu0, sqrt(var2[j]/n2))
      
      S1_list[j] = var1[j] / (n1-1) * rchisq(1, df = n1-1)
      S2_list[j] = var2[j] / (n2-1) * rchisq(1, df = n2-1)
    }
    else {
      mu1_j = rnorm(1, mean = 0, sd = sqrt(mu1 * var1[j]))
      Z1_list[j] = rnorm(1, mu1_j, sqrt(var1[j]/n1))
      Z2_list[j] = rnorm(1, mu2, sqrt(var2[j]/n2))
      
      S1_list[j] = var1[j] / (n1-1) * rchisq(1, df = n1-1)
      S2_list[j] = var2[j] / (n2-1) * rchisq(1, df = n2-1)
    }
  }
  
  output = list('Z1' = Z1_list, 'S1' = S1_list, 'Z2' = Z2_list, 'S2' = S2_list, 'flag_list' = flag_list)
  
  return (output)
}
```

```{r}
Welch_simulator = function(data_generation_parameter, alpha, rounds, equal = FALSE) {
  set.seed(2)
  
  FDP_of_algorithms = rep(0, rounds)
  Power_of_algorithms = rep(0, rounds)
  FDP_of_t = rep(0, rounds)
  Power_of_t = rep(0, rounds)
  diff = rep(0, rounds)
  
  #print('Simulation Start')
  
  for (r in 1:rounds) {
    
    #print(paste('Start of round', r))
    
    output_r = NA
    
    if (equal) {
      output_r = ss_generator_inW(data_generation_parameter)
    }
    else {
      output_r = ss_generator_F(data_generation_parameter)
    }
    
    Z1_list = output_r$Z1
    Z2_list = output_r$Z2
    S1_list = output_r$S1
    S2_list = output_r$S2
    flag_list = output_r$flag_list
    
    n1 = data_generation_parameter$n1
    n2 = data_generation_parameter$n2
    m = data_generation_parameter$m
    
    
    P_list = P_value_Welch(n1, n2, m, Z1_list, Z2_list, S1_list, S2_list)
    discovery = my_BH(P_list, alpha)
    power = Power(discovery, flag_list)
    fdp = FDP(discovery, flag_list)
    Power_of_algorithms[r] = power
    FDP_of_algorithms[r] = fdp
    
    t_stat = (Z1_list - Z2_list) / sqrt(S1_list / n1)
    P_list_t = pt(abs(t_stat), n1-1, lower.tail = FALSE) * 2
    discovery_t = my_BH(P_list_t, alpha)
    power_t = Power(discovery_t, flag_list)
    fdp_t = FDP(discovery_t, flag_list)
    Power_of_t[r] = power_t
    FDP_of_t[r] = fdp_t
    
    #print(c('round' = r, 'power' = power, 'fdp' = fdp))
    #print(paste('End of round', r))
    #print('')
    
    diff[r] = sum(abs(P_list-P_list_t))
  }
  
  Power = mean(Power_of_algorithms)
  FDR = mean(FDP_of_algorithms)
  Power_t = mean(Power_of_t)
  FDR_t = mean(FDP_of_t)
  Diff = mean(diff)
  
  return (c('power' = Power, 'fdr' = FDR, 'power_t' = Power_t, 'fdr_t' = FDR_t, 'diff' = Diff))
  
}
```

```{r}
alpha = 0.1
rounds = 100
data_generation_parameter = data.frame('n1' = 3, 'n2' = 100000, 'k' = 2, 'd1' = 8, 'd2' = 12, 'm' = 5000, 'mu1' = 12, 'mu2' = 0, 'mean_var2' = 6, 'var_var2' = 4, 'pi0' = 0.9, 'mu0' = 0)
```

```{r}
output_r = ss_generator_F(data_generation_parameter)
    
    Z1_list = output_r$Z1
    Z2_list = output_r$Z2
    S1_list = output_r$S1
    S2_list = output_r$S2
    flag_list = output_r$flag_list
    
    n1 = data_generation_parameter$n1
    n2 = data_generation_parameter$n2
    m = data_generation_parameter$m
    
    
    P_list = P_value_Welch(n1, n2, m, Z1_list, Z2_list, S1_list, S2_list)
    discovery = my_BH(P_list, alpha)
    power = Power(discovery, flag_list)
    fdp = FDP(discovery, flag_list)
    
    t_stat = (Z1_list - Z2_list) / sqrt(S1_list / n1)
    P_list_t = pt(abs(t_stat), n1-1, lower.tail = FALSE) * 2
    discovery_t = my_BH(P_list_t, alpha)
    power_t = Power(discovery_t, flag_list)
    fdp_t = FDP(discovery_t, flag_list)
```

```{r}
hist(P_list_t)
hist(P_list)
max(abs(P_list - P_list_t))
plot(P_list, P_list_t)
```


```{r}
c('power' = power, 'fdr' = fdp, 'power_t' = power_t, 'fdr_t' = fdp_t)
```


```{r}
n1_range = c(3,4,5,6,7,8,9)
n2_range = c(1:25)
power_matrix = matrix(0, length(n1_range), length(n2_range))
fdr_matrix = matrix(0, length(n1_range), length(n2_range))
power_t_matrix = matrix(0, length(n1_range), length(n2_range))
fdr_t_matrix = matrix(0, length(n1_range), length(n2_range))
diff_matrix = matrix(0, length(n1_range), length(n2_range))
```

```{r}
n1 = 3
for (n in n2_range) {
  n2 = 2^n
  print(c('n1' = n1, 'n2' = n2))
  data_generation_parameter = data.frame('n1' = n1, 'n2' = n2, 'k' = 2, 'd1' = 8, 'd2' = 12, 'm' = 5000, 'mu1' = 12, 'mu2' = 0, 'mean_var2' = 6, 'var_var2' = 4, 'pi0' = 0.9, 'mu0' = 0)
  result = Welch_simulator(data_generation_parameter, alpha, rounds, FALSE)
  power_matrix[n1-2, n] = result['power']
  fdr_matrix[n1-2, n] = result['fdr']
  power_t_matrix[n1-2, n] = result['power_t']
  fdr_t_matrix[n1-2, n] = result['fdr_t']
  diff_matrix[n1-2, n] = result['diff']
  
}
```

```{r}
plot(n2_range, diff_matrix[1, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[1, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0, 0.3))
lines(n2_range, power_t_matrix[1, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[1, ], type = 'o', pch = 2, col = 'green', lwd = 2)
lines(n2_range, fdr_t_matrix[1, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topleft', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
for (n1 in n1_range) {
  for (n in n2_range) {
    n2 = 2^n
    print(c('n1' = n1, 'n2' = n2))
    data_generation_parameter = data.frame('n1' = n1, 'n2' = n2, 'k' = 2, 'd1' = 8, 'd2' = 12, 'm' = 5000, 'mu1' = 12, 'mu2' = 0, 'mean_var2' = 6, 'var_var2' = 4, 'pi0' = 0.9, 'mu0' = 0)
    result = Welch_simulator(data_generation_parameter, alpha, rounds)
    power_matrix[n1-2, n] = result['power']
    fdr_matrix[n1-2, n] = result['fdr']
    power_t_matrix[n1-2, n] = result['power_t']
    fdr_t_matrix[n1-2, n] = result['fdr_t']
    diff_matrix[n1-2, n] = result['diff']
  } 
}
```

```{r}
for (n1 in n1_range) {
  main = substitute(expression(paste('FDR of Welch Approximation and t-test when ', n[1] == N1)), list(N1 = n1))
  plot(n2_range, fdr_matrix[n1-2, ], type = 'o', pch = 2, lwd = 2, col = 'green', main = eval(main), ylab = 'FDR', xlab = expression(log[2](n[2])), ylim = c(min(min(fdr_matrix[n1-2, ]), min(fdr_t_matrix[n1-2, ])), max(max(fdr_matrix[n1-2, ]), max(fdr_t_matrix[n1-2, ]))), xaxt = 'n')
  lines(n2_range, fdr_t_matrix[n1-2, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
  axis(1, at = n2_range[n2_range %% 2 == 1])
  abline(h = 0.1, col = "red", lwd = 2, lty = 2)
  legend('topright', legend=c("Welch", "t-test"), col = c('green', 'blue'), pch = 2)
}
```



```{r}
for (n1 in n1_range) {
  position = 'topright'
  if (n1 > 3) {
    position = 'bottomright'
  }
  main = substitute(expression(paste('Power of Welch Approximation and t-test when ', n[1] == N1)), list(N1 = n1))
  plot(n2_range, power_matrix[n1-2, ], type = 'o', pch = 2, lwd = 2, col = 'green', main = eval(main), ylab = 'Power', xlab = expression(log[2](n[2])), ylim = c(min(min(power_matrix[n1-2, ]), min(power_t_matrix[n1-2, ])), max(max(power_matrix[n1-2, ]), max(power_t_matrix[n1-2, ]))), xaxt = 'n')
  lines(n2_range, power_t_matrix[n1-2, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
  axis(1, at = n2_range[n2_range %% 2 == 1])
  legend(position, legend=c("Welch", "t-test"), col = c('green', 'blue'), pch = 2)
}
```

```{r}
for (n1 in n1_range) {
  main = substitute(expression(paste('Total Difference in P-value of Welch Approximation and t-test when ', n[1] == N1)), list(N1 = n1))
  plot(n2_range, diff_matrix[n1-2, ], type = 'o', pch = 2, lwd = 2, col = 'green', main = eval(main), ylab = 'Total Diff in P-value', xlab = expression(log[2](n[2])), xaxt = 'n')
  axis(1, at = n2_range[n2_range %% 2 == 1])
}
```

```{r}
plot(n2_range, diff_matrix[2, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[2, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.5))
lines(n2_range, power_t_matrix[2, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[2, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.6))
lines(n2_range, fdr_t_matrix[2, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, diff_matrix[3, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[3, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.1, 0.7))
lines(n2_range, power_t_matrix[3, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[3, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.7))
lines(n2_range, fdr_t_matrix[3, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, diff_matrix[4, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[4, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.75))
lines(n2_range, power_t_matrix[4, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[4, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range, fdr_t_matrix[4, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```
```{r}
plot(n2_range, diff_matrix[5, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[5, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.8))
lines(n2_range, power_t_matrix[5, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range * 5, fdr_matrix[5, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range * 5, fdr_t_matrix[5, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, diff_matrix[6, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[6, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.8))
lines(n2_range, power_t_matrix[6, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[6, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range, fdr_t_matrix[6, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```
```{r}
plot(n2_range, diff_matrix[7, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[7, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.9))
lines(n2_range, power_t_matrix[7, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[7, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range, fdr_t_matrix[7, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
#n1_range = c(3,4,5,6,7,8,9)
#n2_range = c(1:25)
power_vector = as.vector(t(power_matrix))
fdr_vector = as.vector(t(fdr_matrix))
power_t_vector = as.vector(t(power_t_matrix))
fdr_t_vector = as.vector(t(fdr_t_matrix))
diff_vector = as.vector(t(diff_matrix))
```


```{r}
df_welch_converges = data.frame('n1' = rep(n1_range, each = length(n2_range)), 'log_2_n2' = rep(n2_range, length(n1_range)), 'power_welch' = power_vector, 'power_t' = power_t_vector, 'fdr_welch' = fdr_vector, 'fdr_t' = fdr_t_vector, 'diff_p_value' = diff_vector)
```

```{r}
write.csv(df_welch_converges, 'Welch Property Simulation Result/Welch Convergence/Welch_Converges.csv')
```

```{r}
test = read.csv('Welch Property Simulation Result/Welch Convergence/Welch_Converges.csv')
```

```{r}
test$diff[c(1:25)] - diff_matrix[1, ]
```

