---
title: "visualizer"
author: "Wufang Hong"
date: "4/29/2024"
output: pdf_document
---

# Dataloader

```{r}
Full_FDR_Data = read.csv('./Full Data/Full_FDR_Data_test.csv')
Full_Power_Data = read.csv('./Full Data/Full_Power_Data_test.csv')
```

```{r}
Full_Power_Data
```


# Define Plotter

```{r}
Plotter = function(n1, length_n2, Full_FDR_Data, Full_Power_Data) {
  n2_range = c(n1: (n1 + length_n2 - 1))
  FDR_n1 = Full_FDR_Data[Full_FDR_Data$n1 == n1 & (Full_FDR_Data$n2 %in% n2_range), ]
  Power_n1 = Full_Power_Data[Full_Power_Data$n1 == n1 & (Full_Power_Data$n2 %in% n2_range), ]
  
  # FDR with 1D_NPMLE, 2D_NPMLE
  main = substitute(expression(paste('Relation between FDR and ', n[2], ' for 1D_NPMLE and 2D_NPMLE when ', n[1] == N1)), list(N1 = n1))
  plot(FDR_n1$n2, FDR_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = eval(main), cex.main = 0.8, ylim = c(0, 0.2))
  lines(FDR_n1$n2, FDR_n1$X2D_NPMLE, type = 'o', pch = 1, col = 'black', lwd = 2)
  abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
  legend('topleft', c('1D_NPMLE', '2D_NPMLE'), col=c('blue', 'black'), pch = c(0, 1), lwd=2, lty = 1, cex = 0.6)
  
  # FDR with all algorithms
  main = substitute(expression(paste('Relation between FDR and ', n[2], ' for All Algorithms when ', n[1] == N1)), list(N1 = n1))
  plot(FDR_n1$n2, FDR_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = eval(main), cex.main = 0.8, ylim = c(0, max(FDR_n1[, c(3,4,5,6,7)])))
  lines(FDR_n1$n2, FDR_n1$X2D_NPMLE, type = 'o', pch = 1, col = 'black', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$B_F, type = 'o', pch = 5, col = 'pink', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$t_test, type = 'o', pch = 6, col = 'red', lwd = 2)
  abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
  legend('topleft', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'B_F', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'pink', 'red'), pch = c(0,1,2,5,6), lwd=2, lty = 1, cex = 0.6)
  
  # Power with all algorithms
  main = substitute(expression(paste('Relation between Power and ', n[2], ' for All Algorithms when ', n[1] == N1)), list(N1 = n1))
  plot(Power_n1$n2, Power_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'Power', main = eval(main), cex.main = 0.8, ylim = c(min(Power_n1[, c(3,4,5,6,7)]), max(Power_n1[, c(3,4,5,6,7)])))
  lines(Power_n1$n2, Power_n1$X2D_NPMLE, type = 'o', pch = 1, col = 'black', lwd = 2)
  lines(Power_n1$n2, Power_n1$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
  lines(Power_n1$n2, Power_n1$B_F, type = 'o', pch = 5, col = 'pink', lwd = 2)
  lines(Power_n1$n2, Power_n1$t_test, type = 'o', pch = 6, col = 'red', lwd = 2)
  legend(n1 + length_n2 - 2, 2/3*min(Power_n1[, c(3,4,5,6,7)]) + 1/3*max(Power_n1[, c(3,4,5,6,7)]), c('1D_NPMLE', '2D_NPMLE', 'Welch', 'B_F', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'pink', 'red'), pch = c(0,1,2,5,6), lwd=2, lty = 1, cex = 0.6)
}
```


# n1 = 3

```{r}
n1 = 3
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```
# n1 = 4

```{r}
n1 = 4
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = 5

```{r}
n1 = 5
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = 6

```{r}
n1 = 6
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

# n1 = 7

```{r}
n1 = 7
length_n2 = 7
```

```{r}
Plotter(n1, length_n2, Full_FDR_Data, Full_Power_Data)
```

```{r}
FDR_plotter = function(n1, length_n2, Full_FDR_Data) {
  n2_range = c(n1: (n1 + length_n2 - 1))
  FDR_n1 = Full_FDR_Data[Full_FDR_Data$n1 == n1 & (Full_FDR_Data$n2 %in% n2_range), ]
  
  #main = substitute(expression(paste('Relation between FDR and ', n[2], ' for All Algorithms when ', n[1] == N1)), list(N1 = n1))
  #plot(FDR_n1$n2, FDR_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = eval(main), cex.main = 0.8, ylim = c(0, max(FDR_n1[, c(3,4,5,6,7)])))
  plot(FDR_n1$n2, FDR_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', ylim = c(0, max(FDR_n1[, c(3,4,5,6,7,8)], 0.1)), cex.lab = 1)
  lines(FDR_n1$n2, FDR_n1$X2D_NPMLE, type = 'o', pch = 1, col = 'black', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$B_F, type = 'o', pch = 5, col = 'pink', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$Pooled_t, type = 'o', pch = 6, col = 'red', lwd = 2)
  lines(FDR_n1$n2, FDR_n1$EV_NPMLE, type = 'o', pch = 3, col = '#87CEFA', lwd = 2)
  abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
  #legend('topleft', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'B_F', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'pink', 'red'), pch = c(0,1,2,5,6), lwd=2, lty = 1, cex = 0.6)
}

Power_plotter = function(n1, length_n2, Full_Power_Data) {
  n2_range = c(n1: (n1 + length_n2 - 1))
  Power_n1 = Full_Power_Data[Full_Power_Data$n1 == n1 & (Full_Power_Data$n2 %in% n2_range), ]
  
  #main = substitute(expression(paste('Relation between Power and ', n[2], ' for All Algorithms when ', n[1] == N1)), list(N1 = n1))
  #plot(Power_n1$n2, Power_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'Power', main = eval(main), cex.main = 0.8, ylim = c(min(Power_n1[, c(3,4,5,6,7)]), max(Power_n1[, c(3,4,5,6,7)])))
  plot(Power_n1$n2, Power_n1$X1D_NPMLE, type = 'o', pch = 0, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'Power', ylim = c(min(Power_n1[, c(3,4,5,6,7,8)]), max(Power_n1[, c(3,4,5,6,7)])), cex.lab = 1)
  lines(Power_n1$n2, Power_n1$X2D_NPMLE, type = 'o', pch = 1, col = 'black', lwd = 2)
  lines(Power_n1$n2, Power_n1$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
  lines(Power_n1$n2, Power_n1$B_F, type = 'o', pch = 5, col = 'pink', lwd = 2)
  lines(Power_n1$n2, Power_n1$Pooled_t, type = 'o', pch = 6, col = 'red', lwd = 2)
  lines(Power_n1$n2, Power_n1$EV_NPMLE, type = 'o', pch = 3, col = '#87CEFA', lwd = 2)
  #legend(n1 + length_n2 - 2, 2/3*min(Power_n1[, c(3,4,5,6,7)]) + 1/3*max(Power_n1[, c(3,4,5,6,7)]), c('1D_NPMLE', '2D_NPMLE', 'Welch', 'B_F', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'pink', 'red'), pch = c(0,1,2,5,6), lwd=2, lty = 1, cex = 0.6)
}
```


```{r}
#par(mfrow = c(3,2))
png("combined_plot_with_legend.png", width = 3200, height = 2400, res = 300)
par(mfrow = c(3, 2), mar = c(2.5,2.5,2.5,2.5), oma = c(0, 0, 0, 13), mgp = c(1.5, 0.5, 0))
FDR_plotter(3,7,Full_FDR_Data)
Power_plotter(3,7,Full_Power_Data)
FDR_plotter(5,7,Full_FDR_Data)
Power_plotter(5,7,Full_Power_Data)
FDR_plotter(7,7,Full_FDR_Data)
Power_plotter(7,7,Full_Power_Data)
#par(mfrow = c(1,1))
par(xpd = NA)
legend('topright', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'B_F', 'Pooled_t_test', 'EV_PMLE'), col=c('blue', 'black', 'green', 'pink', 'red', '#87CEFA'), pch = c(0,1,2,5,6,3), lwd=2, lty = 1, cex = 1.5, inset = c(-0.5, -2.66))
dev.off()
```


# n1 = n2

```{r}
FDR_equ = Full_FDR_Data[Full_FDR_Data$n1 == Full_FDR_Data$n2, ]
main = expression(paste('Relation between FDR and ', n[2], ' for All Algorithms when ', n[1], ' = ', n[2]))
plot(FDR_equ$n2, FDR_equ$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'FDR', main = main, cex.main = 0.8, ylim = c(0, max(FDR_equ[, c(3,4,5,6)])))
lines(FDR_equ$n2, FDR_equ$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
lines(FDR_equ$n2, FDR_equ$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
lines(FDR_equ$n2, FDR_equ$Pooled_t, type = 'o', pch = 2, col = 'red', lwd = 2)
abline(h = 0.1, lwd = 2, col = 'grey', lty = 2)
legend('bottomleft', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'red'), lwd=2, lty = 1, cex = 0.7)
```

```{r}
Power_equ = Full_Power_Data[Full_Power_Data$n1 == Full_Power_Data$n2, ]
main = expression(paste('Relation between Power and ', n[2], ' for All Algorithms when ', n[1], ' = ', n[2]))
plot(Power_equ$n2, Power_equ$X1D_NPMLE, type = 'o', pch = 2, col = 'blue', lwd = 2, xlab = expression(n[2]), ylab = 'Power', main = main, cex.main = 0.8, ylim = c(0, max(Power_equ[, c(3,4,5,6)])))
lines(Power_equ$n2, Power_equ$X2D_NPMLE, type = 'o', pch = 2, col = 'black', lwd = 2)
lines(Power_equ$n2, Power_equ$Welch, type = 'o', pch = 2, col = 'green', lwd = 2)
lines(Power_equ$n2, Power_equ$Pooled_t, type = 'o', pch = 2, col = 'red', lwd = 2)
legend('bottomright', c('1D_NPMLE', '2D_NPMLE', 'Welch', 'Pooled_t_test'), col=c('blue', 'black', 'green', 'red'), lwd=2, lty = 1, cex = 0.7)
```


