---
title: "BF Simulation"
author: "Wufang Hong"
date: "5/25/2024"
output: pdf_document
---

```{r}
library(asht)
```

# BH, Power, FDR

```{r}
my_BH = function(P, alpha) {
  n = length(P)
  sorted_index = order(P, decreasing = FALSE)
  k_list = which(P[sorted_index][1:n] <= (1:n) * alpha / n)
  if (length(k_list) == 0) {
    return (c())
  }
  else {
    k = max(k_list)
    discovery = sorted_index[1:k]
    return (discovery)
  }
}
```

```{r}
Power = function(discovery, flag_list) {
  dis_count = sum(flag_list)
  true_dis_count = sum(flag_list[discovery])
  power = true_dis_count/dis_count
  return (power)
}
```

```{r}
FDP = function(discovery, flag_list) {
  #null_count = length(flag_list) - sum(flag_list)
  false_null = length(discovery) - sum(flag_list[discovery])
  fdp = false_null/max(length(discovery) ,1)
  return (fdp)
}
```

```{r}
data_generator = function(data_generation_parameter) {
  
  n1=data_generation_parameter$n1
  n2=data_generation_parameter$n2
  k=data_generation_parameter$k
  d1=data_generation_parameter$d1
  d2=data_generation_parameter$d2
  m=data_generation_parameter$m
  mu1=data_generation_parameter$mu1
  mu2=data_generation_parameter$mu2
  mean_var2 = data_generation_parameter$mean_var2
  var_var2 = data_generation_parameter$var_var2
  pi0 = data_generation_parameter$pi0
  mu0 = data_generation_parameter$mu0
  
  null_count = as.integer(pi0 * m)
  dis_count = m - null_count
  flag_list = c(rep(0, null_count), rep(1, dis_count)) # 0 for null, 1 for truth
  
  lambda = k * rf(m, d1, d2)
  var2 = abs(rnorm(m, mean_var2, sqrt(var_var2)))
  var1 = lambda * var2
  
  X1 = matrix(0, m, n1)
  X2 = matrix(0, m, n2)
  
  for (j in 1:m) {
    if (j <= null_count) {
      X1[j, ] = rnorm(n1, mu0, sqrt(var1[j]))
      X2[j, ] = rnorm(n2, mu0, sqrt(var2[j]))
    }
    else {
      X1[j, ] = rnorm(n1, rnorm(1, mean = 0, sd = sqrt(mu1 * var1[j])), sqrt(var1[j]))
      X2[j, ] = rnorm(n2, mu2, sqrt(var2[j]))
    }
  }
  
  output = list('X1' = X1, 'X2' = X2, 'flag_list' = flag_list)
  
  return (output)
}
```

```{r}
BF_simulator = function(data_generation_parameter, alpha, rounds) {
  set.seed(2)
  
  FDP_of_algorithms = rep(0, rounds)
  Power_of_algorithms = rep(0, rounds)
  
  #print('Simulation Start')
  n1 = data_generation_parameter$n1
  n2 = data_generation_parameter$n2
  m = data_generation_parameter$m
  
  for (r in 1:rounds) {
    
    print(paste('Start of round', r))
    
    output_r = data_generator(data_generation_parameter)
    
    X1 = output_r$X1
    X2 = output_r$X2
    flag_list = output_r$flag_list

    
    P_list_r = rep(0, m)
    
    for (i in c(1:m)) {
      X1_i = X1[i, ]
      X2_i = X2[i, ]
      P_i = bfTest(X1_i, X2_i, mu = 0)$p.value
      P_list_r[i] = P_i
    }
    
    discovery = my_BH(P_list_r, alpha)
    power = Power(discovery, flag_list)
    fdp = FDP(discovery, flag_list)
    Power_of_algorithms[r] = power
    FDP_of_algorithms[r] = fdp
  }
  
  Power = mean(Power_of_algorithms)
  FDR = mean(FDP_of_algorithms)
  
  return (c('power' = Power, 'fdr' = FDR))
  
}
```

```{r}
n1_range = c(3,4,5,6,7)
power_matrix = matrix(0, length(n1_range), 7)
fdr_matrix = matrix(0, length(n1_range), 7)
```

```{r}
nrow(power_matrix)
ncol(power_matrix)
write.table(data.frame('n1','n2', 'power', 'fdr'), file = './B_F.csv', sep = ',', col.names = FALSE, row.names = FALSE)
```

```{r}
for (n1 in n1_range) {
  for (n2 in seq(n1, n1 + 6)) {
    print(c('n1' = n1, 'n2' = n2))
    rounds = 50
    alpha = 0.1
    data_generation_parameter = data.frame('n1' = n1, 'n2' = n2, 'k' = 2, 'd1' = 8, 'd2' = 12, 'm' = 5000, 'mu1' = 12, 'mu2' = 0, 'mean_var2' = 6, 'var_var2' = 4, 'pi0' = 0.9, 'mu0' = 0)
    result = BF_simulator(data_generation_parameter, alpha, rounds)
    power_matrix[n1-2, n2-n1+1] = result['power']
    fdr_matrix[n1-2, n2-n1+1] = result['fdr']
    
    data_n1_n2 = data.frame('n1' = n1, 'n2' = n2, 'power' = result['power'], 'fdr' = result['fdr'])
    write.table(data_n1_n2, file = './B_F.csv', sep = ',', col.names = FALSE, row.names = FALSE, append = TRUE)
  }
}
```

```{r}
n2_list = c()
for (n1 in n1_range) {
  for (n2 in seq(n1, n1 + 9)) {
    n2_list = c(n2_list, n2)
  }
}
```

```{r}
n1_list = rep(n1_range, each = 10)
```

```{r}
df_bf_test = data.frame('n1' = n1_list, 'n2' = n2_list, 'power' = as.vector(t(power_matrix)), 'fdr' = as.vector(t(fdr_matrix)))
```

```{r}
write.csv(df_bf_test, 'bf_test.csv')
```

# Visualize

```{r}
plot(n2_range, diff_matrix[1, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[1, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0, 0.3))
lines(n2_range, power_t_matrix[1, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[1, ], type = 'o', pch = 2, col = 'green', lwd = 2)
lines(n2_range, fdr_t_matrix[1, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topleft', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
for (n1 in c(4:9)) {
  for (j in c(1:length(n2_range))) {
    n2 = 2^n2_range[j]
    print(c('n1' = n1, 'n2' = n2))
    data_generation_parameter = data.frame('n1' = n1, 'n2' = n2, 'k' = 2, 'd1' = 8, 'd2' = 12, 'm' = 5000, 'mu1' = 12, 'mu2' = 0, 'mean_var2' = 6, 'var_var2' = 4, 'pi0' = 0.9, 'mu0' = 0)
    result = Welch_simulator(data_generation_parameter, alpha, rounds)
    power_matrix[n1-2, j] = result['power']
    fdr_matrix[n1-2, j] = result['fdr']
    power_t_matrix[n1-2, j] = result['power_t']
    fdr_t_matrix[n1-2, j] = result['fdr_t']
    diff_matrix[n1-2, j] = result['diff']
  } 
}
```

```{r}
plot(n2_range, diff_matrix[2, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[2, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.5))
lines(n2_range, power_t_matrix[2, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[2, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.6))
lines(n2_range, fdr_t_matrix[2, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, diff_matrix[3, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[3, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.1, 0.7))
lines(n2_range, power_t_matrix[3, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[3, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.7))
lines(n2_range, fdr_t_matrix[3, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, diff_matrix[4, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[4, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.75))
lines(n2_range, power_t_matrix[4, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[4, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range, fdr_t_matrix[4, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```
```{r}
plot(n2_range, diff_matrix[5, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[5, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.8))
lines(n2_range, power_t_matrix[5, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range * 5, fdr_matrix[5, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range * 5, fdr_t_matrix[5, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, diff_matrix[6, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[6, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.8))
lines(n2_range, power_t_matrix[6, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[6, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range, fdr_t_matrix[6, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```
```{r}
plot(n2_range, diff_matrix[7, ], type = 'o', pch = 2, col = 'green', lwd = 2)
```

```{r}
plot(n2_range, power_matrix[7, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.2, 0.9))
lines(n2_range, power_t_matrix[7, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("power_welch", "power_t"), col = c('green', 'blue'), pch = 2)
```

```{r}
plot(n2_range, fdr_matrix[7, ], type = 'o', pch = 2, col = 'green', lwd = 2, ylim = c(0.05, 0.8))
lines(n2_range, fdr_t_matrix[7, ], type = 'o', pch = 2, col = 'blue', lwd = 2)
legend('topright', legend=c("fdr_welch", "fdr_t"), col = c('green', 'blue'), pch = 2)
```



