---
title: "Rejection Region Pooled"
output: pdf_document
date: "2024-11-09"
---

# Hedenfalk

```{r}
library(Equalden.HD)
data(Hedenfalk)
source('EPB.R')
source('helper z.R')
```

```{r}
nrow(Hedenfalk)
```

```{r}
head(Hedenfalk)
```

```{r}
X1 = Hedenfalk[, 1:7]
X2 = Hedenfalk[, 8:15]
```

```{r}
info = information_extractor(X1, X2)
```

```{r}
tau_list = info$S1_list/info$S2_list

log_tau_list = log(tau_list)

log_tau_list = log_tau_list[log(tau_list) >= -5]

tau_grid = exp(seq(min(log_tau_list), max(log_tau_list), length.out = 1000))
```

Samples for test

```{r}
X1_1 = X1[1, ]
X2_1 = X2[1, ]
K1 = length(X1_1)
K2 = length(X2_1)
m1 = mean(X1_1)
m2 = mean(X2_1)
sd1 = sqrt(var(X1_1))
sd2 = sqrt(var(X2_1))
se = sqrt(sd2^2/K2)
md = m1 - m2
t = md / se
```

Range of sample t_BF to determine range of root solver

```{r}
t_z_list = c()

for (i in 1:nrow(Hedenfalk)) {
  m1_i = mean(X1[i, ])
  m2_i = mean(X2[i, ])
  s1_i = var(X1[i, ])
  s2_i = var(X2[i, ])
  t_z_i = (m1_i - m2_i) / sqrt(s2_i/K2)
  t_z_list = c(t_z_list, t_z_i)
}

max(t_z_list)

t_z_list = t_z_list[log(tau_list) >= -5]
```

```{r}
result_csv = read.csv('./Result/2D_Hedenfalk.csv')
```

```{r}
grid = result_csv[, 2:3]
mass = result_csv[, 4]
```

```{r}
#target = sort(abs(log_tau_list), decreasing = TRUE)[1:50]

#sort(D[abs(log_tau_list) %in% target] / median(D))

#cbind(info$S1_list[log(tau_list) >= -5][abs(log_tau_list) %in% target], info$S2_list[log(tau_list) >= -5][abs(log_tau_list) %in% target], D[abs(log_tau_list) %in% target] / median(D))
```

```{r}
cutoff_1DNPMLE = 0.0026508907
cutoff_2DNPMLE = 0.0030585356
cutoff_Welch = 0.0002270525
cutoff_pooled_t = 0.0038435845
cutoff_B_F = -Inf
cutoff_EV_NPMLE = 0.0035106845
```

```{r}
grid_1D = grid_2D[, 1] / grid_2D[, 2]
```

# Beherens-Fisher test

```{r}
bfresult = bfTest(X1_1, X2_1)
bfresult
z_pvalue_BF(t, sd1^2/sd2^2, K1, K2)
z_pvalue_BF_solver_positive(sd1^2/sd2^2, K1, K2, 0.05)
```

```{r}
t_BF_005 = c()

for (tau in tau_grid) {
  t_BF_005_i = z_pvalue_BF_solver_positive(tau, K1, K2, 0.05)
  t_BF_005 = append(t_BF_005, t_BF_005_i)
}
```

```{r}
t_BF_bh = c()

for (tau in tau_grid) {
  t_BF_bh_i = z_pvalue_BF_solver_positive(tau, K1, K2, 0.1)
  t_BF_bh = append(t_BF_bh, t_BF_bh_i)
}
```

# 1DNPMLE

```{r}
p_value_npmle_j(K1, K2, m1, m2, sd1^2, sd2^2, grid_1D, mass, sd1^2/sd2^2)
z_pvalue_1DNPMLE(t, K1, K2, grid_1D, mass, sd1^2/sd2^2)
z_pvalue_1DNPMLE_solver_positive(K1, K2, grid_1D, mass, sd1^2/sd2^2, 0.05)
```

```{r}
t_1DNPMLE_005 = c()
t_1DNPMLE_bh = c()

for (tau in tau_grid) {
  t_1DNPMLE_005_i = z_pvalue_1DNPMLE_solver_positive(K1, K2, grid_1D, mass, tau, 0.05)
  t_1DNPMLE_bh_i = z_pvalue_1DNPMLE_solver_positive(K1, K2, grid_1D, mass, tau, cutoff_1DNPMLE)
  t_1DNPMLE_005 = append(t_1DNPMLE_005, t_1DNPMLE_005_i)
  t_1DNPMLE_bh = append(t_1DNPMLE_bh, t_1DNPMLE_bh_i)
}
```

# Welch

```{r}
Welch_approximation_p(K1, K2, m1, m2, sd1^2, sd2^2)
z_pvalue_Welch(t, sd1^2/sd2^2, K1, K2)
z_pvalue_Welch_solver_positive(sd1^2/sd2^2, K1, K2, 0.05)
t
```

```{r}
t_Welch_005 = c()
t_Welch_bh = c()

for (tau in tau_grid) {
  t_Welch_005_i = z_pvalue_Welch_solver_positive(tau, K1, K2, 0.05)
  t_Welch_bh_i = z_pvalue_Welch_solver_positive(tau, K1, K2, cutoff_Welch)
  t_Welch_005 = append(t_Welch_005, t_Welch_005_i)
  t_Welch_bh = append(t_Welch_bh, t_Welch_bh_i)
}
```

# Pooled t-test

```{r}
t.test(X1_1, X2_1, var.equal = TRUE)$p.value
z_pvalue_t(t, sd1^2/sd2^2, K1, K2)
z_pvalue_t_solver_positive(sd1^2/sd2^2, K1, K2, 0.05)
t
```

```{r}
t_t_005 = c()
t_t_bh = c()

for (tau in tau_grid) {
  t_t_005_i = z_pvalue_t_solver_positive(tau, K1, K2, 0.05)
  t_t_bh_i = z_pvalue_t_solver_positive(tau, K1, K2, cutoff_pooled_t)
  t_t_005 = append(t_t_005, t_t_005_i)
  t_t_bh = append(t_t_bh, t_t_bh_i)
}
```

# Visualization

```{r}
plot_2D = function(u1,u2) {
  ggplot(data.frame(u1 = u1, u2 = u2), aes(x = u1, y = u2)) +
    stat_bin2d(bins = 200) +
    scale_fill_gradient(low = "lightblue", high = "darkblue") +
    labs(x = "u1", y = "u2", fill = "Count") +
    scale_y_continuous(limits = c(-20, 20)) +
    theme_minimal()
}
```

```{r}
plot_2D(log_tau_list, t_z_list) + 
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_BF_005), aes(x = log_tau_grid, y = y, color = 'BF (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_BF_005), aes(x = log_tau_grid, y = y, color = 'BF (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_1DNPMLE_005), aes(x = log_tau_grid, y = y, color = '1D-NPMLE (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_1DNPMLE_005), aes(x = log_tau_grid, y = y, color = '1D-NPMLE (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_Welch_005), aes(x = log_tau_grid, y = y, color = 'Welch (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_Welch_005), aes(x = log_tau_grid, y = y, color = 'Welch (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_t_005), aes(x = log_tau_grid, y = y, color = 'Pooled t (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_t_005), aes(x = log_tau_grid, y = y, color = 'Pooled t (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_BF_bh), aes(x = log_tau_grid, y = y, color = 'BF (BH)')) +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_BF_bh), aes(x = log_tau_grid, y = y, color = 'BF (BH)')) +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_1DNPMLE_bh), aes(x = log_tau_grid, y = y, color = '1D-NPMLE (BH)')) +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_1DNPMLE_bh), aes(x = log_tau_grid, y = y, color = '1D-NPMLE (BH)')) +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_Welch_bh), aes(x = log_tau_grid, y = y, color = 'Welch (BH)')) +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_Welch_bh), aes(x = log_tau_grid, y = y, color = 'Welch (BH)')) +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_t_bh), aes(x = log_tau_grid, y = y, color = 'Pooled t (BH)')) +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_t_bh), aes(x = log_tau_grid, y = y, color = 'Pooled t (BH)')) +
  
  scale_color_manual(name = '', values = c('1D-NPMLE (BH)' = 'blue', 'BF (BH)' = 'pink', 'Welch (BH)' = 'green', 'Pooled t (BH)' = 'red', '1D-NPMLE (unadj.)' = 'blue', 'BF (unadj.)' = 'pink', 'Welch (unadj.)' = 'green', 'Pooled t (unadj.)' = 'red')) + 
  labs(x = expression(hat(lambda[i])), y = expression(T[i]^{z})) + theme_minimal()
```

```{r}
plot_2D(log_tau_list, t_z_list) + 
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_BF_005), aes(x = log_tau_grid, y = y, color = 'BF (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_BF_005), aes(x = log_tau_grid, y = y, color = 'BF (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_1DNPMLE_005), aes(x = log_tau_grid, y = y, color = '1D-NPMLE (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_1DNPMLE_005), aes(x = log_tau_grid, y = y, color = '1D-NPMLE (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_Welch_005), aes(x = log_tau_grid, y = y, color = 'Welch (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_Welch_005), aes(x = log_tau_grid, y = y, color = 'Welch (unadj.)'), linetype = 'dashed') +
  
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = t_t_005), aes(x = log_tau_grid, y = y, color = 'Pooled t (unadj.)'), linetype = 'dashed') +
  geom_line(data = data.frame(log_tau_grid = log(tau_grid), y = -t_t_005), aes(x = log_tau_grid, y = y, color = 'Pooled t (unadj.)'), linetype = 'dashed') +
  
  scale_color_manual(name = '', values = c('1D-NPMLE (BH)' = 'blue', 'BF (BH)' = 'pink', 'Welch (BH)' = 'green', 'Pooled t (BH)' = 'red', '1D-NPMLE (unadj.)' = 'blue', 'BF (unadj.)' = 'pink', 'Welch (unadj.)' = 'green', 'Pooled t (unadj.)' = 'red')) + 
  labs(x = expression(hat(lambda[i])), y = expression(T[i]^{z})) + theme_minimal()
```

```{r}
par(mar = c(5, 4, 4, 8))

plot(log(tau_grid), t_BF_005, type = 'l', ylim = c(-30, 30), lwd = 2, col = 'pink', xlab = expression(hat(lambda[i])), ylab = expression(T[i]^{z}), lty=2)
lines(log(tau_grid), -t_BF_005, lwd = 2, col = 'pink', lty=2)
#lines(log(tau_grid), t_BF_bh, lwd = 2, col = 'pink')
#lines(log(tau_grid), -t_BF_bh, lwd = 2, col = 'pink')

lines(log(tau_grid), t_1DNPMLE_005, lwd = 2, col = 'blue', lty=2)
lines(log(tau_grid), -t_1DNPMLE_005, lwd = 2, col = 'blue', lty=2)
#lines(log(tau_grid), t_1DNPMLE_bh, lwd = 2, col = 'blue')
#lines(log(tau_grid), -t_1DNPMLE_bh, lwd = 2, col = 'blue')

lines(log(tau_grid), t_Welch_005, lwd = 2, col = 'green', lty=2)
lines(log(tau_grid), -t_Welch_005, lwd = 2, col = 'green', lty=2)
#lines(log(tau_grid), t_Welch_bh, lwd = 2, col = 'green')
#lines(log(tau_grid), -t_Welch_bh, lwd = 2, col = 'green')

lines(log(tau_grid), t_t_005, lwd = 2, col = 'red', lty=2)
lines(log(tau_grid), -t_t_005, lwd = 2, col = 'red', lty=2)
#lines(log(tau_grid), t_t_bh, lwd = 2, col = 'red')
#lines(log(tau_grid), -t_t_bh, lwd = 2, col = 'red')

#legend('topright', c('1D_NPMLE (BH)', 'Welch (BH)', 'B_F (BH)', 'Pooled_t (BH)', '1D_NPMLE (unadj.)', 'Welch (unadj.)', 'B_F (unadj.)', 'Pooled_t (unadj.)'), col=c('blue', 'green', 'pink', 'red', 'blue', 'green', 'pink', 'red'), lwd=2, lty = c(1,1,1,1,2,2,2,2), cex = 0.7, inset = c(-0.32, 0), xpd = TRUE)
legend('topright', c('1D_NPMLE (unadj.)', 'Welch (unadj.)', 'B_F (unadj.)', 'Pooled_t (unadj.)'), col=c('blue', 'green', 'pink', 'red'), lwd=2, lty = c(2,2,2,2), cex = 0.7, inset = c(-0.32, 0), xpd = TRUE)
```

